### PR TITLE
this fps scorch is insane

### PR DESCRIPTION
**Pull request by camelStyleUser**

### CODE REVIEW

**Comment by camelStyleUser** [comment]
@RouterXdd should i the bundle commit

**Comment by camelStyleUser** [comment]
this fps scorch wont be fixed
you love fps scorches it seems

**Comment by RouterXdd** [comment]
-_-
I dont have them

**Comment by RouterXdd** [comment]
Plus I had pushed commit when I notice this pull request
So I cannot merge him

**Comment by camelStyleUser** [comment]
> -_- I dont have them

check the commits
and the docs

**Comment by camelStyleUser** [comment]
heal() is a flat increase, it doesnt use Time.delta

**Comment by RouterXdd** [comment]
https://github.com/RouterXdd/Icicle-World/commit/8dabf06063150e8c2675a56550174abc3fdeb11a

**Pull request closed without merging**
